### ISSUE TITLE
heatmaps for normal images are not clear

### ISSUE THREAD

**Issue by clarezei** [dhkdnduq/PatchCore_anomaly_detection#13]
Hi, thanks for your efforts,
I tried to visualize heatmap, 
but the quality for normal images is terrible, 
I noticed you'd answered this question in [hcw-00](https://github.com/hcw-00/PatchCore_anomaly_detection/issues/14#issuecomment-894992092),
you said 'You have to use min,max of all the data.'
I tried but the results are still terrible (anomalous image became normal),
could you explain this in detail?
I first collect all the anomaly_map, and their max, min values in the list,
and then get the max of all the max values, min of all the min values, 
then use them to normalize every anomaly map.

**Comment by dhkdnduq** [comment]
> Hi, thanks for your efforts, I tried to visualize heatmap, but the quality for normal images is terrible, I noticed you'd answered this question in [hcw-00](https://github.com/hcw-00/PatchCore_anomaly_detection/issues/14#issuecomment-894992092), you said 'You have to use min,max of all the data.' I tried but the results are still terrible (anomalous image became normal), could you explain this in detail? I first collect all the anomaly_map, and their max, min values in the list, and then get the max of all the max values, min of all the min values, then use them to normalize every anomaly map.

1.Store all anomaly maps.  * self.all_scores = []

2.Normalization 

        min_score = np.min(score_pathces)
        max_score = np.max(score_pathces)
        scores = (score_pathces - min_score) / (max_score - min_score)

**Comment by clarezei** [comment]
thanks for your prompt reply!
> 1,1,1,0,1,1,0 (X)
> 0,1,1,1,4,1,1 (O)

does 0 represent normal, and 1 represent abnormal?
what does 4 represent here?

**Comment by dhkdnduq** [comment]
> thanks for your prompt reply!
> 
> > 1,1,1,0,1,1,0 (X)
> > 0,1,1,1,4,1,1 (O)
> 
> does 0 represent normal, and 1 represent abnormal? what does 4 represent here?
> 
> If I use normalization for an individual image, the heatmap is okay, but normal image will be abnormal; however if I use the max and min values of all heatmaps, some anomalous images became normal...

In my opinion, the situation is as follows.

When the heat map is correctly displayed

normal score[ 0,1,0,1]
abnormal score[5,6,6,7]

----------------------------------------------------
When the heat map is not correctly displayed(your situation)

normal score[ 0,1,0,1]
abnormal score[5,6,6,100]
5, 6, and 6 are colors close to normal.

Limit the value of max score.
