### ISSUE TITLE
sum(2) in distance_matix consumes a lot of time

### ISSUE THREAD

**Issue by x12901** [dhkdnduq/PatchCore_anomaly_detection#8]
after distance_matix, gpu->cpu slows down,maybe libtorch problem.
https://discuss.pytorch.org/t/copy-tensor-from-cuda-to-cpu-is-too-slow/13056
I add `torch::cuda::synchronize();` 
`torch::pow(x - y, p).sum(2);` Is it the cause of the slowdown and can it be improved?
My program took 80ms, this step took 51ms.
```
torch::Tensor distance_matix(torch::Tensor x, torch::Tensor y, int p = 2) {
	auto n = x.size(0);
	auto m = y.size(0);
	auto d = x.size(1);
	x = x.unsqueeze(1).expand({ n,m,d });
	y = y.unsqueeze(0).expand({ n,m,d }); 
	torch::cuda::synchronize();
	double e1 = cv::getTickCount();
	torch::pow(x - y, p).sum(2);
	torch::cuda::synchronize();
	double e2 = cv::getTickCount();
	std::cout << "distance_matix " << (e2 - e1) / cv::getTickFrequency() << std::endl;
	return dist;
}
```

**Comment by dhkdnduq** [comment]
Improvement for performance

auto dist = torch::pow( distance_matix(embedding_vectors, anomaly_feature_patchcore[category], p), (1 / (float)p));
->
auto dist =  torch::cdist(embedding_vectors, anomaly_feature_patchcore[category], p);

**Comment by x12901** [comment]
Thank you , this solves my problem.
