### ISSUE TITLE
where is full libtorch code?

### ISSUE THREAD

**Issue by ingbeeedd** [dhkdnduq/PatchCore_anomaly_detection#9]
I wonder that

**Comment by dhkdnduq** [comment]
Refer to main.more than 95% of the code is implemented.

**Comment by ingbeeedd** [comment]
@dhkdnduq 

is that "Readme 2. Support Libtorch " ?

**Comment by dhkdnduq** [comment]
> @dhkdnduq
> 
> is that "Readme 2. Support Libtorch " ?

do you mean libtorch git?

https://pytorch.org/get-started/locally/

**Comment by ingbeeedd** [comment]
@dhkdnduq 
I just wanted to see the c++ code (based libtorch) for patchcore!

**Comment by dhkdnduq** [comment]
> @dhkdnduq I just wanted to see the c++ code (based libtorch) for patchcore!

Readme  2.Support Libtorch

**Comment by ingbeeedd** [comment]
@dhkdnduq 
I'm curious. How did you make the bottom part? Can you implement train with C++? `anomaly_feature_patchcore[category]`

**Comment by dhkdnduq** [comment]
> @dhkdnduq I'm curious. How did you make the highlight variable? Can you implement train with C++? `anomaly_feature_patchcore[category]`
wrong variable , it is anomaly_features . 
train only python

**Comment by ingbeeedd** [comment]
@dhkdnduq 
Did you build and use the torchvision c++ source yourself?

**Comment by ingbeeedd** [comment]
@dhkdnduq 

```python
class TrainFeature(torch.jit.ScriptModule):
    #__constants__ = ['feature']

    def __init__(self,feature_):
        super(TrainFeature, self).__init__()
        #self.feature = feature_
        self.register_buffer('feature', feature_)
    def forward(self):
        pass
```

Why did you script the embedding data as above?
